# This is a basic workflow to help you get started with Actions

name: documentation-generation

# Controls when the action will run. 
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  generate-documentation:
    runs-on: windows-latest
    defaults:
      run:
        shell: pwsh
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Run documentation generation
        run: |
          echo 'Workspace directory is ${{ github.workspace }}'
          & "${{ github.workspace }}\build\IfcDocLite.exe" "${{ github.workspace }}\IFC4x3" -D "${{ github.workspace }}\documentation" "${{ github.workspace }}\IFC4x3\figures"
          dir documentation
          dir IFC4x3
      - name: Upload documentation
        uses: actions/upload-artifact@v3
        with:
          name: IFC Documentation
          path: ${{ github.workspace }}\documentation
